package me.bjxg.demo.mock.user.model;

import javax.persistence.Table;

@Table(name="tb_user")
public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.USERNAME
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.REALNAE
     *
     * @mbggenerated
     */
    private String realnae;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.PHONE
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.ID
     *
     * @return the value of TB_USER.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.ID
     *
     * @param id the value for TB_USER.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.USERNAME
     *
     * @return the value of TB_USER.USERNAME
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.USERNAME
     *
     * @param username the value for TB_USER.USERNAME
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.REALNAE
     *
     * @return the value of TB_USER.REALNAE
     *
     * @mbggenerated
     */
    public String getRealnae() {
        return realnae;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.REALNAE
     *
     * @param realnae the value for TB_USER.REALNAE
     *
     * @mbggenerated
     */
    public void setRealnae(String realnae) {
        this.realnae = realnae == null ? null : realnae.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.PHONE
     *
     * @return the value of TB_USER.PHONE
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.PHONE
     *
     * @param phone the value for TB_USER.PHONE
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}